c****************************************************************************
c ... DO NOT EDIT.  AUTOMATICALLY GENERATED FILE.
c****************************************************************************
c ...
c ... CKWYP-compatible GETRATES: return molar production rates for all
c ... species given pressure (P), temperature (T), and mass fractions (Y).
c ...
c ... Generated by cgetrates 1.0b
c ...
c****************************************************************************

      subroutine getrates(P,T,Y,ICKWRK,RCKWRK,WSPL)

      implicit none

      integer    NSMax               ! maximum number of species
      parameter (NSMax = 1000)
      integer    NRMax               ! maximum number of reactions
      parameter (NRMax = 5000)

      real PA            ! atm. pressure; dyne/cm^2
      parameter (PA  = 1.013250d+06)
      real R0            ! gas constant; erg/(mol K)
      parameter (R0  = 8.314510d+07)
      real R0c           ! gas constant; cal/(mol K)
      parameter (R0c = 1.9872155832)
      real DLn10         ! log(10)
      parameter (DLn10 = 2.3025850929940459d0)

      integer          ICKWRK(*)     ! ...
      real RCKWRK(*)     ! ...
      real P             ! pressure
      real T             ! temperature (K)
      real Y(NSMax)      ! ...
      real WSPL(NSMax)   ! ...

      real FCent         ! ...
      real FDenom        ! ...
      real FLogPR        ! ...
      real FQuan         ! ...
      real CTOT          ! ...
      real OPRT          ! ...
      real ORTC          ! ...
      real OTC           ! ...
      real PR            ! ...
      real PRT           ! ...
      real RC            ! ...
      real RR_F          ! forward reaction rate
      real RR_R          ! reverse reaction rate
      real RR_K0         ! ...
      real RR_KInf       ! ...
      real TC            ! ...
!      real THBCTEMP      ! ...   ! for generating code, don't use this THBCTEMP
      real VLNPRT        ! ...
      real VLNTEMP       ! ...
      real XIK           ! ...

      real CGSPL(NSMax)  ! ...
      real CSPL(NSMax)   ! ...
      real ROPL(NRMax)   ! ...

      integer          KSP           ! ...
      integer          I             ! loop index

      intrinsic exp, log
      external  CKRHOY, CKYTCP
      integer NC_H, NC_H2, NC_O, NC_OH, NC_H2O, NC_O2, NC_HO2,
     & NC_H2O2, NC_N2

      parameter (NC_H                 =   1)
      parameter (NC_H2                =   2)
      parameter (NC_O                 =   3)
      parameter (NC_OH                =   4)
      parameter (NC_H2O               =   5)
      parameter (NC_O2                =   6)
      parameter (NC_HO2               =   7)
      parameter (NC_H2O2              =   8)
      parameter (NC_N2                =   9)

      integer    NS                 ! number of species
      parameter (NS                   =   9)
c----------------------------------------------------------------------------
c ... loop over all cells

c$doacross local(i,j,tc,rc,otc,vlntemp,cgspl,ksp,wspl,cspl,rr_f,rr_r,
c$&              xik,ctot,ropl,pr,fcent,thbctemp,rr_k0,rr_kinf,flogpr,
c$&              fdenom,fquan,prt,vlnprt),
c$&        share(m,n,temp,rho,temp1tab,odtab,ns,cgsptab,ys,ospwt,spwt,
c$&              temptab,wchem,tempref)

cmic$  do all
cmic$* private(xik,ctot,ropl,pr,fcent,thbctemp,rr_k0,rr_kinf,flogpr)
cmic$* private(i,j,tc,rc,otc,vlntemp,cgspl,ksp,wspl,cspl,rr_f,rr_r)
cmic$* private(fdenom,fquan,prt,vlnprt)
cmic$* shared(m,n,temp,rho,temp1tab,odtab,ns,cgsptab,ys,ospwt,spwt)
cmic$* shared(temptab,wchem,tempref)

c----------------------------------------------------------------------------

      TC = T

      call CKRHOY(P,T,Y,ICKWRK,RCKWRK,RC)

      otc     = 1.0 / tc
      ortc    = 1.0 / (tc * R0c)
      vlntemp = log(TC)
      prt     = PA / (R0 * TC)
      oprt    = 1.0 / prt
      vlnprt  = log(prt)

c ... get gibbs free energies

c inlined
c     call getcgsp(i,j,cgspl)

      call CKGML(T,ICKWRK,RCKWRK,CGSPL)

      do I=1,NS
         CGSPL(I) = CGSPL(I) / R0
      end do

c ... initialize

c     do ksp=1,ns
c        cspl(ksp)  = rc*ys(i,j,ksp)*ospwt(ksp)           ! concentrations
c     end do

      call CKYTCP(P,T,Y,ICKWRK,RCKWRK,CSPL) ! mass fraction => molar concentration (for each species) in CSPL

      prt = pa / (r0 * tc)
      vlnprt = log(prt)
c----------------------------------------
c ... calculate third-body concentrations
      ctot = 0.0
      do ksp = 1, ns
        ctot = ctot + cspl(ksp) ! chemkin2000: Eq.(63), alpha_ki=1.0
      end do
!      thbctemp(2) = ctot + 1.5d+000*cspl(NC_H2) + 1.1d+001*cspl(NC_H2O) ! alpha_H2_i=2.5=1+1.5, alpha_H2O_i=12.0=1+11 
!      thbctemp(3) = ctot - 2.7d-001*cspl(NC_H2) + 2.65d+000*cspl(NC_H2O)
!     &  
!      thbctemp(4) = ctot + 2.7d+000*cspl(NC_H2) + 2.0d-001*cspl(NC_O2)
!     &   + 6.65d+000*cspl(NC_H2O) + 6.7d+000*cspl(NC_H2O2) + 5.0d-001*
!     &  cspl(NC_N2)
!      thbctemp(5) = ctot + 3.0d-001*cspl(NC_H2) + 9.0d+000*cspl(NC_H2O)
!      wspl(1) = TC
!      wspl(2) = otc
!      wspl(3) = ortc
!      wspl(4) = vlntemp
!      wspl(5) = prt     
!      wspl(6) = oprt
!      wspl(7) = cgspl(1)
!      wspl(8) = cspl(1)
c----------------------------------------------------
c      1)  H+O2 = O+OH 
      rr_f =  1.04000000000000d+14 * exp(-1.52860000000000d+04 * ortc)
      xik = -1.0 * cgspl(NC_H) -1.0 * cgspl(NC_O2) +
     & 1.0 * cgspl(NC_O) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(1) = rr_f * cspl(NC_H) * cspl(NC_O2) -
     & rr_r * cspl(NC_O) * cspl(NC_OH)
c      2)  O+H2 = H+OH 
      rr_f =  3.81800000000000d+12 * exp(-7.94800000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_O) -1.0 * cgspl(NC_H2) +
     & 1.0 * cgspl(NC_H) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(2) = rr_f * cspl(NC_O) * cspl(NC_H2) -
     & rr_r * cspl(NC_H) * cspl(NC_OH)
c      3)  O+H2 = H+OH 
      rr_f =  8.79200000000000d+14 * exp(-1.91700000000000d+04 * ortc)
      xik = -1.0 * cgspl(NC_O) -1.0 * cgspl(NC_H2) +
     & 1.0 * cgspl(NC_H) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(3) = rr_f * cspl(NC_O) * cspl(NC_H2) -
     & rr_r * cspl(NC_H) * cspl(NC_OH)
c      4)  H2+OH = H2O+H 
      rr_f =  2.16000000000000d+08 *
     & exp( 1.51000000000000d+00*vlntemp -3.43000000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_H2) -1.0 * cgspl(NC_OH) +
     & 1.0 * cgspl(NC_H2O) + 1.0 * cgspl(NC_H)
      rr_r = rr_f * exp(xik*otc)
      ropl(4) = rr_f * cspl(NC_H2) * cspl(NC_OH) -
     & rr_r * cspl(NC_H2O) * cspl(NC_H)
c      5)  OH+OH = O+H2O 
      rr_f =  3.34000000000000d+04 *
     & exp( 2.42000000000000d+00*vlntemp + 1.93000000000000d+03 * ortc)
      xik = -2.0 * cgspl(NC_OH) + 1.0 * cgspl(NC_O) +
     & 1.0 * cgspl(NC_H2O)
      rr_r = rr_f * exp(xik*otc)
      ropl(5) = rr_f * cspl(NC_OH) * cspl(NC_OH) -
     & rr_r * cspl(NC_O) * cspl(NC_H2O)
#ifdef USE_THIRD_BODY
c      6)  H2+M = H+H+M 
      rr_f =  4.57700000000000d+19 *
     & exp(-1.40000000000000d+00*vlntemp -1.04380000000000d+05 * ortc)
      xik = -1.0 * cgspl(NC_H2) + 2.0 * cgspl(NC_H)
      rr_r = rr_f * exp(xik*otc) * oprt
      ropl(6) = rr_f * cspl(NC_H2) - rr_r * cspl(NC_H) * cspl(NC_H)
      ropl(6) = ropl(6) * (ctot +
     & 1.50000000000000d+00 * cspl(NC_H2) +
     & 1.10000000000000d+01 * cspl(NC_H2O))
c      7)  O+O+M = O2+M 
      rr_f =  6.16500000000000d+15 *
     & exp(-5.00000000000000d-01*vlntemp -0.00000000000000d+00 * ortc)
      xik = -2.0 * cgspl(NC_O) + 1.0 * cgspl(NC_O2)
      rr_r = rr_f * exp(xik*otc) * prt
      ropl(7) = rr_f * cspl(NC_O) * cspl(NC_O) - rr_r * cspl(NC_O2)
      ropl(7) = ropl(7) * (ctot +
     & 1.50000000000000d+00 * cspl(NC_H2) +
     & 1.10000000000000d+01 * cspl(NC_H2O))
c      8)  O+H+M = OH+M 
      rr_f =  4.71400000000000d+18 *
     & exp(-1.00000000000000d+00*vlntemp -0.00000000000000d+00 * ortc)
      xik = -1.0 * cgspl(NC_O) -1.0 * cgspl(NC_H) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc) * prt
      ropl(8) = rr_f * cspl(NC_O) * cspl(NC_H) - rr_r * cspl(NC_OH)
      ropl(8) = ropl(8) * (ctot +
     & 1.50000000000000d+00 * cspl(NC_H2) +
     & 1.10000000000000d+01 * cspl(NC_H2O))
c      9)  H2O+M = H+OH+M 
      rr_f =  6.06400000000000d+27 *
     & exp(-3.32200000000000d+00*vlntemp -1.20790000000000d+05 * ortc)
      xik = -1.0 * cgspl(NC_H2O) + 1.0 * cgspl(NC_H) +
     & 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc) * oprt
      ropl(9) = rr_f * cspl(NC_H2O) - rr_r * cspl(NC_H) * cspl(NC_OH)
      ropl(9) = ropl(9) * (ctot +
     & 2.00000000000000d+00 * cspl(NC_H2) -
     & 1.00000000000000d+00 * cspl(NC_H2O) +
     & 1.00000000000000d+00 * cspl(NC_N2) +
     & 5.00000000000000d-01 * cspl(NC_O2))
c      10)  H2O+H2O = H+OH+H2O 
      rr_f =  1.00600000000000d+26 *
     & exp(-2.44000000000000d+00*vlntemp -1.20180000000000d+05 * ortc)
      xik = -1.0 * cgspl(NC_H2O) + 1.0 * cgspl(NC_H) +
     & 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc) * oprt
      ropl(10) = rr_f * cspl(NC_H2O) * cspl(NC_H2O) -
     & rr_r * cspl(NC_H) * cspl(NC_OH) * cspl(NC_H2O)
#endif
#ifdef USE_TROE
c      11)  H+O2(+M) = HO2(+M) 
      rr_k0 =  6.36600000000000d+20 *
     & exp(-1.72000000000000d+00*vlntemp -5.24800000000000d+02 * ortc)
      rr_kinf =  4.65084000000000d+12 *
     & exp( 4.40000000000000d-01*vlntemp -0.00000000000000d+00 * ortc)
      pr = rr_k0 / rr_kinf *(ctot +
     & 1.00000000000000d+00 * cspl(NC_H2) +
     & 1.30000000000000d+01 * cspl(NC_H2O) -
     & 2.20000000000000d-01 * cspl(NC_O2))
      fcent = log10( 5.00000000000000d-01 *
     & exp(-1.00000000000000d+30 * tc) +
     & 5.00000000000000d-01 * exp(-1.00000000000000d-30 * tc))
      flogpr = log10(pr) - 0.4 - 0.67 * fcent
      fdenom = 0.75 - 1.27 * fcent - 0.14 * flogpr
      fquan = flogpr / fdenom
      fquan = fcent / (1.0 + fquan * fquan)
      rr_f = rr_kinf * pr/(1.0 + pr) * exp(fquan*dln10) 
      xik = -1.0 * cgspl(NC_H) -1.0 * cgspl(NC_O2) + 1.0 * cgspl(NC_HO2)
      rr_r = rr_f * exp(xik*otc) * prt
      ropl(11) = rr_f * cspl(NC_H) * cspl(NC_O2) - rr_r * cspl(NC_HO2)
#endif
c      12)  HO2+H = H2+O2 
      rr_f =  2.75000000000000d+06 *
     & exp( 2.09000000000000d+00*vlntemp + 1.45100000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_HO2) -1.0 * cgspl(NC_H) +
     & 1.0 * cgspl(NC_H2) + 1.0 * cgspl(NC_O2)
      rr_r = rr_f * exp(xik*otc)
      ropl(12) = rr_f * cspl(NC_HO2) * cspl(NC_H) -
     & rr_r * cspl(NC_H2) * cspl(NC_O2)
c      13)  HO2+H = OH+OH 
      rr_f =  7.07900000000000d+13 * exp(-2.95000000000000d+02 * ortc)
      xik = -1.0 * cgspl(NC_HO2) -1.0 * cgspl(NC_H) + 2.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(13) = rr_f * cspl(NC_HO2) * cspl(NC_H) -
     & rr_r * cspl(NC_OH) * cspl(NC_OH)
c      14)  HO2+O = O2+OH 
      rr_f =  2.85000000000000d+10 *
     & exp( 1.00000000000000d+00*vlntemp + 7.23930000000000d+02 * ortc)
      xik = -1.0 * cgspl(NC_HO2) -1.0 * cgspl(NC_O) +
     & 1.0 * cgspl(NC_O2) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(14) = rr_f * cspl(NC_HO2) * cspl(NC_O) -
     & rr_r * cspl(NC_O2) * cspl(NC_OH)
c      15)  HO2+OH = H2O+O2 
      rr_f =  2.89000000000000d+13 * exp( 4.97000000000000d+02 * ortc)
      xik = -1.0 * cgspl(NC_HO2) -1.0 * cgspl(NC_OH) +
     & 1.0 * cgspl(NC_H2O) + 1.0 * cgspl(NC_O2)
      rr_r = rr_f * exp(xik*otc)
      ropl(15) = rr_f * cspl(NC_HO2) * cspl(NC_OH) -
     & rr_r * cspl(NC_H2O) * cspl(NC_O2)
c      16)  HO2+HO2 = H2O2+O2 
      rr_f =  4.20000000000000d+14 * exp(-1.19820000000000d+04 * ortc)
      xik = -2.0 * cgspl(NC_HO2) + 1.0 * cgspl(NC_H2O2) +
     & 1.0 * cgspl(NC_O2)
      rr_r = rr_f * exp(xik*otc)
      ropl(16) = rr_f * cspl(NC_HO2) * cspl(NC_HO2) -
     & rr_r * cspl(NC_H2O2) * cspl(NC_O2)
c      17)  HO2+HO2 = H2O2+O2 
      rr_f =  1.30000000000000d+11 * exp( 1.62930000000000d+03 * ortc)
      xik = -2.0 * cgspl(NC_HO2) + 1.0 * cgspl(NC_H2O2) +
     & 1.0 * cgspl(NC_O2)
      rr_r = rr_f * exp(xik*otc)
      ropl(17) = rr_f * cspl(NC_HO2) * cspl(NC_HO2) -
     & rr_r * cspl(NC_H2O2) * cspl(NC_O2)
#ifdef USE_TROE
c      18)  H2O2(+M) = OH+OH(+M) 
      rr_k0 =  2.49000000000000d+24 *
     & exp(-2.30000000000000d+00*vlntemp -4.87490000000000d+04 * ortc)
      rr_kinf =  2.00000000000000d+12 *
     & exp( 9.00000000000000d-01*vlntemp -4.87490000000000d+04 * ortc)
      pr = rr_k0 / rr_kinf *(ctot +
     & 6.50000000000000d+00 * cspl(NC_H2O) +
     & 5.00000000000000d-01 * cspl(NC_N2) +
     & 2.00000000000000d-01 * cspl(NC_O2) +
     & 6.70000000000000d+00 * cspl(NC_H2O2) +
     & 2.70000000000000d+00 * cspl(NC_H2))
      fcent = log10( 5.70000000000000d-01 *
     & exp(-1.00000000000000d+30 * tc) +
     & 4.30000000000000d-01 * exp(-1.00000000000000d-30 * tc))
      flogpr = log10(pr) - 0.4 - 0.67 * fcent
      fdenom = 0.75 - 1.27 * fcent - 0.14 * flogpr
      fquan = flogpr / fdenom
      fquan = fcent / (1.0 + fquan * fquan)
      rr_f = rr_kinf * pr/(1.0 + pr) * exp(fquan*dln10) 
      xik = -1.0 * cgspl(NC_H2O2) + 2.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc) * oprt
      ropl(18) = rr_f * cspl(NC_H2O2) - rr_r * cspl(NC_OH) * cspl(NC_OH)
#endif
c      19)  H2O2+H = H2O+OH 
      rr_f =  2.41000000000000d+13 * exp(-3.97000000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_H2O2) -1.0 * cgspl(NC_H) +
     & 1.0 * cgspl(NC_H2O) + 1.0 * cgspl(NC_OH)
      rr_r = rr_f * exp(xik*otc)
      ropl(19) = rr_f * cspl(NC_H2O2) * cspl(NC_H) -
     & rr_r * cspl(NC_H2O) * cspl(NC_OH)
c      20)  H2O2+H = HO2+H2 
      rr_f =  4.82000000000000d+13 * exp(-7.95000000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_H2O2) -1.0 * cgspl(NC_H) +
     & 1.0 * cgspl(NC_HO2) + 1.0 * cgspl(NC_H2)
      rr_r = rr_f * exp(xik*otc)
      ropl(20) = rr_f * cspl(NC_H2O2) * cspl(NC_H) -
     & rr_r * cspl(NC_HO2) * cspl(NC_H2)
c      21)  H2O2+O = OH+HO2 
      rr_f =  9.55000000000000d+06 *
     & exp( 2.00000000000000d+00*vlntemp -3.97000000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_H2O2) -1.0 * cgspl(NC_O) +
     & 1.0 * cgspl(NC_OH) + 1.0 * cgspl(NC_HO2)
      rr_r = rr_f * exp(xik*otc)
      ropl(21) = rr_f * cspl(NC_H2O2) * cspl(NC_O) -
     & rr_r * cspl(NC_OH) * cspl(NC_HO2)
c      22)  H2O2+OH = HO2+H2O 
      rr_f =  1.74000000000000d+12 * exp(-3.18000000000000d+02 * ortc)
      xik = -1.0 * cgspl(NC_H2O2) -1.0 * cgspl(NC_OH) +
     & 1.0 * cgspl(NC_HO2) + 1.0 * cgspl(NC_H2O)
      rr_r = rr_f * exp(xik*otc)
      ropl(22) = rr_f * cspl(NC_H2O2) * cspl(NC_OH) -
     & rr_r * cspl(NC_HO2) * cspl(NC_H2O)
c      23)  H2O2+OH = HO2+H2O 
      rr_f =  7.59000000000000d+13 * exp(-7.27000000000000d+03 * ortc)
      xik = -1.0 * cgspl(NC_H2O2) -1.0 * cgspl(NC_OH) +
     & 1.0 * cgspl(NC_HO2) + 1.0 * cgspl(NC_H2O)
      rr_r = rr_f * exp(xik*otc)
      ropl(23) = rr_f * cspl(NC_H2O2) * cspl(NC_OH) -
     & rr_r * cspl(NC_HO2) * cspl(NC_H2O)
c-----------------------------------------------------------------------
c ... evaluate contributions to reactants and products
c H    
      wspl(NC_H) = -ropl(1)+ ropl(2)+ ropl(3)+ ropl(4)+
     & 2.0*ropl(6)- ropl(8)+ ropl(9)+
     & ropl(10)- ropl(11)- ropl(12)- ropl(13)- ropl(19)- ropl(20)
c H2    
      wspl(NC_H2) = -ropl(2)- ropl(3)- ropl(4)- ropl(6)+
     & ropl(12)+ ropl(20)
c H2O    
      wspl(NC_H2O) = ropl(4)+ ropl(5)- ropl(9)- ropl(10)+
     & ropl(15)+ ropl(19)+ ropl(22)+ ropl(23)
c H2O2    
      wspl(NC_H2O2) = ropl(16)+
     & ropl(17)- ropl(18)- ropl(19)- ropl(20)- ropl(21)-
     & ropl(22)- ropl(23)
c HO2    
      wspl(NC_HO2) = ropl(11)- ropl(12)- ropl(13)- ropl(14)-
     & ropl(15)- 2.0*ropl(16)- 2.0*ropl(17)+ ropl(20)+ ropl(21)+
     & ropl(22)+ ropl(23)
c O    
      wspl(NC_O) = ropl(1)- ropl(2)- ropl(3)+
     & ropl(5)- 2.0*ropl(7)- ropl(8)- ropl(14)- ropl(21)
c O2    
      wspl(NC_O2) = -ropl(1)+ ropl(7)- ropl(11)+ ropl(12)+
     & ropl(14)+ ropl(15)+ ropl(16)+ ropl(17)
c OH    
      wspl(NC_OH) = ropl(1)+ ropl(2)+
     & ropl(3)- ropl(4)- 2.0*ropl(5)+ ropl(8)+ ropl(9)+
     & ropl(10)+ 2.0*ropl(13)+ ropl(14)- ropl(15)+ 2.0*ropl(18)+
     & ropl(19)+ ropl(21)- ropl(22)- ropl(23)
c N2
      wspl(NC_N2) = 0.0
c-----------------------------------------------------------------------
      return
      end
